### PR TITLE
Build changes

### PR DESCRIPTION
**Pull request by adamboutcher**
This should enable Mac M1 Builds and fix some issues with the Windows build not working correctly.
We do however lose Mac 32bit builds but I doubt they're needed.

### CODE REVIEW

**Comment by adamboutcher** [comment]
@jemand771 Can you double check I've not done anything stupid please?

**Review by jemand771 — APPROVED** [review]
I don't see anything that's obviously wrong, but the only way to know for sure is to test it :b

**Comment by jemand771** [comment]
Note that github uses the workflow files from the default branch (dev, which you're merging into) for all branches - not the one on the current branch

A way to test this would be putting the workflow file on dev in a fork and trying the merge there, but I don't reaally have time for that right now :c

**Comment by adamboutcher** [comment]
I tested it on my own fork and it worked, I just wanted to make sure it looked sane to someone else incase I broke something obvious to others.

Thank you for your review.

**Pull request merged**
