### PR TITLE
Refactor GitHub actions workflows

### LINKED ISSUE #125: V0.90.80 Docker build fails
Docker build is failing on stable action.

### PR DESCRIPTION
**Pull request by jemand771**
I'm trying to squish all of the build-related workflows into one as it doesn't make a lot of sense to maintain three different copies of what is essentially the same thing. There's still a lot wrong with the current state but I'll use this PR to track progress and potentially and discuss some general things (once it actually works lol)

A quick list of things that are wrong (might be incomplete, I've also added TODO comments)
- [x] windows and mac builds fail (i might have messed something up there - I think they _used to_ work)
- [x] the build step still creates a release
- [ ] docker doesn't use the metadata action yet
- [x] general if-conditions to decide between release and dev builds
- [ ] aws
- [ ] test job is failing
- [x] job dependencies might not be fully correct (i'll re-arrange the jobs anyway)
- [ ] original workflows still exist - if build.yml does everything it's supposed to, we can delete the stable, unstable, dev and pr-test yml files
- [ ] bump node version (see dev branch)
- [ ] bump go version (see dev branch)
- [ ] put a central variable for node/go versoins somewhere (at least within the workflows)

I've also gone ahead and:
* merge the two dockerfiles into one
* remove (hopefully) everything refering to the :base and :vue docker tags
* clean up the makefile according to the changes above

final note: I know some of the commit messages aren't that great. I'll rebase once everything works

### CODE REVIEW

**Comment by adamboutcher** [comment]
Oh WOW! This is great work!

**Comment by jemand771** [comment]
hmm, my local branch is currently failing a single postman test. I haven't used postman before but it sounds like this might be related to the hosted runners not working (?)
https://github.com/statping-ng/statping-ng/blob/dev/dev/postman.json#L4602-L4651
from what I can see, this performs requests to statping.com so we probably don't want to keep that in anyway

no clue why it works on statping-ng/statping-ng and not on my local fork though (or: why it works on self-hosted runners but not the github-hosted ones)

**Comment by adamboutcher** [comment]
So I believe this is the "Email" Notifier rather than "SMTP mail".
And the end-point that statping uses (news.statping.com) is actually offline, probably an idea to remove this completely unless we can find an alternative as I don't think we can do this via github hosting.

https://github.com/statping-ng/statping-ng/issues/3#issuecomment-919156655

**Comment by adamboutcher** [comment]
How close are we with this? The self hosted runners I setup have broke so I'm trying to judge if to merge this or fix the runners...

**Comment by jemand771** [comment]
hmm, to be honest I completely forgot about this D:
I'm gonna see what's missing and try to get it to a usable state

**Comment by adamboutcher** [comment]
I've managed to fix my runners again. :-)

**Comment by jemand771** [comment]
@adamboutcher remind me, what's the naming scheme for the docker tags and registries?

registries:
* dockerhub: `adamboutcher/statping-ng` -> owned by you, accessible to actions via `DOCKER_USERNAME` and `DOCKER_PASSWORD`
* GitHub container registry: `ghcr.io/statping-ng/statping-ng` -> belongs to the statping-ng organization, accessible from workflows by default (I think)
* ... do we want/need more? I don't really see an advantage

tags:
* for pushes to stable, the docker tag should be called `v{major}.{minor}.{patch}` according to the version.txt
  * this also updates the `latest` tag
  * I'd also populate the `v{major}.{minor}` and `v{major}` tags - it's somewhat good practice and convenient for people who want to stick to one specific major/minor version without missing patches
  * just as a note: it's common to name docker tags without the `v` prefix, but in this case sticking to the original naming is probably more desirable
* for pushes to unstable, build the `dev` tag
  * suggestion: since a release/git tag `dev-v{major}.{minor}.{patch}` is created - should we also create that as a docker tag? pro: targettable docker builds for unstable, con: might "clutter" the registries - which isn't really an issue as the overviews are usually sorted by last push (and you don't have to look there often anyway)
* for pushes to dev, ... no docker push happens? do we want a static dev tag? naming it might get difficult (since stable -> `:latest` and unstable -> `:dev`)
* do we want to push docker images for PRs and/or individual commits? this might speed up testing but also adds a lot of probably never used images to the registry (I'd call them `pr-<number>` e.g. pr-123 and `sha-<hash>` e.g. `sha-abc123d`)
  * I'm probably going to have the actions workflow attach the built image as an artifact to the workflow. this way, it's also possible to take the image from there instead of the registry (download file and `docker load`)
  * this probably requires the image to get uniquely tagged anyway - it's just a matter of publishing it to dockerhub/ghcr or not

those are mostly just what I remembered and some additional ideas, feel free to correct me wherever needed! (it's been a while)

**Comment by adamboutcher** [comment]
We currently have dockerhub and quay.io registries, dockerhub is a push, quay.io pulls from the repo (somehow).

At the moment I've only been incrementing the `{patch}` version number but thats becasue I've got no real plans on how/what changes the `{major}` or `{minor}` numbering. Also, storing the version number in a file feels very clunky, if you have better ideas then now's the time to change this. As even the snaps feel really hacked together rather than cohesive with the main build.

`dev` and `unstable` branches were just added so we could have a working `:dev` container  from `unstable` while we got a handle on things to allow `dev` to break, I think these should really merge together and become `:testing` container and completely re-thing/organise the branches, however this might need someone that understand git management to work out, my git knowledge is 75% from looking after this repo now :-D

Ideas/improvements overall is highly welcome.

**Comment by jemand771** [comment]
the best way would probably be to manually create a tag/release and have github actions populate the artifacts and docker registries for it afterwards. the only downside to this is that for a couple of minutes/hours, there will be a release listed that's not actually out yet

in that case, we'd only really need one branch: dev (I'm fine with that name, it would have the same use as master/main)
we could:
* build the dev branch to :dev or :testing or whatever on every push
* create a release on tag creation (with corresponding docker tag and attached binaries and all)
* still run the workflow on each push/pr, without creating a github release (but potentially pushing a PR-specific docker image for testing)
  * we could also have that be something like ghcr.io/statping-ng/statping-ng-testing - that way, it's a different image name and should be obvious that it shouldn't be used

an alternative would be to have a "release workflow" in actions that you can manually trigger. (you can give optional input parameters to github actions workflows when manually triggered). that solution doesn't feel as clean though

**Comment by jemand771** [comment]
oh, and about the docker registries: ghcr is really easy to use (both from a publishing and a user point of view), that's why I'd like to add it. dockerhub is pretty much the default, so having that is also a good idea. I can look into the quay.io at some point (you can probably disable the "pulling" somehow and manually push there)

**Comment by adamboutcher** [comment]
> an alternative would be to have a "release workflow" in actions that you can manually trigger. (you can give optional input parameters to github actions workflows when manually triggered). that solution doesn't feel as clean though

This might be a much more simple way? Means we only have one branch and we could tag every release?

**Comment by adamboutcher** [comment]
> > an alternative would be to have a "release workflow" in actions that you can manually trigger. (you can give optional input parameters to github actions workflows when manually triggered). that solution doesn't feel as clean though
> 
> This might be a much more simple way? Means we only have one branch and we could tag every release?

If we do this then we might even get away with not running the full tests on release, as long as we run the functional tests on every commit and that we can check that the last one succeeded.

**Comment by jemand771** [comment]
I would have preferred creating a draft release on github -> populated by actions -> manually publish but that doesn't work (workflows ignore draft events). the only way to do this would be to create a pre-release and have the workflow pick that up but.. that's not ideal (publicly visible+might forget to check the prerelease box+"abusing" prereleases), so we're probably going with the manual workflow trigger approach

soo I'm gonna do something like:
* build+test pull requests and pushes to dev (the default branch)
* have an input for the target release version as 3 numbers
* built+test and release on manual triggers, tagged like we previously would pushes to stable
  * not sure if this should be part of the build workflow or its own "release" workflow that triggers build. I'll see how well it integrates

this has some side effects:
* no need for stable/unstable branches anymore
* probably some changes needed elsewhere to get rid of the version.txt (we can do that seperately as long as we don't let them get out of sync)
* no more pre-releases

also, I'd keep :latest in sync with the latest release and :dev in sync with the most recent commit on the dev branch (which might not be released yet)

**Comment by adamboutcher** [comment]
Only issue I can see is if it builds successfully but it's still broken elsewhere? How do we handle the roll back?

Does this also leave us with a testing/unstable build and a known working build?

**Comment by jemand771** [comment]
well, the current stable build would be the same as the last release - with the artifacts in the github release section, and a docker image tagges as :v1.2.3 and :latest. the unstable/testing build will be available as artifacts from github actions (default retention: 90 days) and as a docker image via the :dev tag

I'm not sure what you mean by successful broken builds. the binaries working while the docker images don't? that shouldn't happen unless someone changes the build system

**Comment by jonathanrbarney** [comment]
Put in a hacky fix for the failing go tests on the dev branch workflows. The secrets.SLACK_URL is not valid for whatever reason so I overwrote it with a valid one I found somewhere in the source.

**Comment by jemand771** [comment]
I don't think hardcoding a slack url is a good idea D:
(especially since it seems like it's sensitive/a webhook?)

as for the bumped go and node versions - node `16.14.0` and go `1.17.8` ? there's still go `1.15` left in some places, is that intentional? if not, I'll bump it globally for the new workflows

**Comment by jonathanrbarney** [comment]
I don't manage that slack so IDK what the url is for, but the alternative is creating our own slack with an app with a webhook then adding that to github secrets (which I can't manage for this repo). As far as sensitivity it was already in the source code in a tests file so I am not worried about that, maybe just that it is randomly notifying a slack channel somewhere lol.

RE: GO versions, I attempted to update those to the new go version, but I had two issues:
- the latest supported go version for actions in this way is 1.17.7 not 1.17.8 (give it time)
- When running it with this updated go version I got some error message about go tool version not matching 1.15.5 or something similar when running the dev pipeline (which now works). 

Sidenote, I also see that same error message when running the PR action (which I was trying to get working but took a break from)

So leaving those where they are for now

**Pull request closed without merging**
