### PR TITLE
Fix Custom OAuth scopes parameter

### LINKED ISSUE #165: Custom OAuth request uses the wrong request parameter
After setting up a custom OAuth provider (Discord), attempting to log-in using the provider returns an error stating "No scopes were provided."

This is because the parameter defining scopes in the URL statping-ng generates is actually written as `scopes`. [According to RFC 6749, the parameter should be `scope`.](https://www.rfc-editor.org/rfc/rfc6749#section-3.3)

Edit: It also seems that `scope` should be space-delimited - statping-ng generates the url with scopes separated by a comma.
Per RFC 6749:
> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.

### PR DESCRIPTION
**Pull request by sn8to**
https://www.rfc-editor.org/rfc/rfc6749#section-3.3

This PR (hopefully) fixes statping-ng/statping-ng#165

### CODE REVIEW

**Comment by jemand771** [comment]
thanks for you contribution! :D looks good so far, I'll test this soon™

this makes me wonder if anyone is actually using this feature, and if so, if it will break for them. I guess if so it's their fault for not following the spec

**Comment by sn8to** [comment]
That's what I was thinking as well, but if their OAuth provider is breaking spec then is it really our fault anyways? 🙃 

I'm figuring out how to test on my personal machine - if I ever get it working right then I'll post an update.

**Review by falvhb — APPROVED** [review]
Fine according to https://datatracker.ietf.org/doc/html/rfc6749#page-23
Testet with Azure oAuth and only "scope" parameter is accepeted.

**Comment by KNIF** [comment]
Any update on this? Merging this PR would fix the oAuth method.

@jemand771 could you please review this PR

**Pull request closed without merging**
