### PR TITLE
Add header validation to prevent service panic.

### PR DESCRIPTION
**Pull request by EdisonFu**
if user set header xxx without "="，services will crash due to array overflow. 
So, I made the following modifications to check the validity of the header.

### CODE REVIEW

**Comment by EdisonFu** [comment]
image

Hello, this is the screenshot of the check failure. I don't believe it's due to the code modifications I made. The issue seems to be related to the configuration of GOPROXY. Could you please take a look at it?

**Comment by jemand771** [comment]
probably not on you, no.
since this only happened in one of the postman runs (but they should all be identical), I'm gonna call this a fluke. re-run timee

**edit:** oh look, it's worse now. _sigh_

**Comment by EdisonFu** [comment]
> probably not on you, no. since this only happened in one of the postman runs (but they should all be identical), I'm gonna call this a fluke. re-run timee
> 
> **edit:** oh look, it's worse now. _sigh_


Thank you for your reply. I think this problem is caused by the upgrade of golang version. You can refer to this issue in golang's official project, maybe need your help to manually configure GOPROXY！  

https://github.com/golang/go/issues/62274

**Comment by EdisonFu** [comment]
> > probably not on you, no. since this only happened in one of the postman runs (but they should all be identical), I'm gonna call this a fluke. re-run timee
> > **edit:** oh look, it's worse now. _sigh_
> 
> Thank you for your reply. I think this problem is caused by the upgrade of golang� version. You can refer to this issue in golang's official project, maybe need your help to manually configure GOPROXY！
> 
> [golang/go#62274](https://github.com/golang/go/issues/62274)

@jemand771  Would you mind confirm whether this problem caused the failure of the checks?  Thanks

**Comment by OstlerDev** [comment]
Hi! The issues with the postman test pipelines is because we need to change a couple things.

1. Add `GOPROXY` to environment variables
2. Update Go to 1.21.8 for the test workflows

I have included fixes in my other pull request here: https://github.com/statping-ng/statping-ng/pull/257

Here are the commits with the changes I made to fix the build:
- https://github.com/statping-ng/statping-ng/pull/257/commits/422de34b099390846ffe5a3d43e7b3516e38029d Include `GOPROXY` in Environment Variables
- https://github.com/statping-ng/statping-ng/pull/257/commits/144df9c5aa3a2455691cffd8fc7c53ca6077aca2 Use Go v1.21.8 for running the Postman tests

I would say this one can likely be merged in, since the test failures have nothing to do with the code you have changed here 😸 I could prepare a side Merge Request just for fixing the builds if you would also like, then we could merge the fix into dev and back into your branch.

**Comment by OstlerDev** [comment]
Okay, to make things simpler for everyone I made a Merge Request just for fixing the Postman Tests/builds: https://github.com/statping-ng/statping-ng/pull/282

That has all the changes needed to fix the tests.

**Comment by EdisonFu** [comment]
> Okay, to make things simpler for everyone I made a Merge Request just for fixing the Postman Tests/builds: #282
> 
> That has all the changes needed to fix the tests.

Cool !  
So what do I need to do next？  Or do I just wait for the code to merge?

**Comment by jemand771** [comment]
@EdisonFu you don't need to do anything, thanks :D

I'll take a look at ci soon™. Feel free to bump me after a while if I forget

**Pull request merged**
