### PR TITLE
dev: Add base.gohtml in assets [#137](https://github.com/statping-ng/…

### LINKED ISSUE #130: [Feature Request] Script tag support for Footer/Head
It would be good to be able to throw google analytics and other scripts into the header/footer. This would require that a header html field be added in the control panel and allow for script tags in the footer field as well as the proposed header config field.

Currently, we try a `document.write(new Date())` in our Copywrite notice in the footer but that fails to actually run. I would like to replace the text Name in the header of the page with our logo but I cannot seem to find an easy way to do this. I could easily do this with JS script tags in the header or even in the footer, but as mentioned before it appears the script tags do not function.

### LINKED ISSUE #137: Add base.gohtml in assets too
Just logging the issue to match an incoming PR.
This would be useful for additionnal theming to have access to this template.

### PR DESCRIPTION
**Pull request by geoffroya**
…statping-ng/issues/137)

### CODE REVIEW

**Comment by adamboutcher** [comment]
Hi, Can you explain what this does?

**Comment by geoffroya** [comment]
Sure!
If you ask for externalized assets (CSS...), you will also get the base.gohtml file, so one can change it, for example in my use-case, remove the embedded favicon, to be more white-labelled.

**Comment by adamboutcher** [comment]
What's the reason for the change in the api.js? Do we need to change the version too?

Apologies, I dont know go at all so treat me like a 5yo :-P 

Otherwise I think it looks good

**Comment by geoffroya** [comment]
I think the API.js is just updated with the commit ID, during `make`. Doesn't change the API at all.
BTW I see that I left from debug logging messages, I'm gonna remove them.

And I don't know go either ;)

**Comment by geoffroya** [comment]
> Do we need to change the version too?

IMHO, the version should reflect the version that will be release. Current stable is 0.90.80.
So it seems fair that next is 0.91.00

**Comment by adamboutcher** [comment]
I think the next version due is v0.90.81

**Comment by geoffroya** [comment]
I depends if you see it as a fix or new feature.

**Comment by adamboutcher** [comment]
So far we've  decided to keep the versions similar to the original statping to not break any apps etc.

x.nn.yy
x = Breaking changes
nn = Major Updates (possible breakages)
yy = Minor changes

Everything has been a minor change so far.

**Comment by geoffroya** [comment]
Please to take it personnaly, but why are you arguing about the version number?
I even didn't commit it. It was what is was in the `dev` branch, which is - acording to https://github.com/statping-ng/statping-ng/wiki/Contributing - the target branch for any PR.

I assume that when one will make a release, one will update target version in `dev` branch, test, merge to `stable`, tag and release.
And in `dev`, bump it back to `0.91.00`.

Am I wrong?

**Comment by adamboutcher** [comment]
Was just informing you that's all. No worries 🙃

**Comment by Fireant456** [comment]
@geoffroya How would this solve my issue if I personally want to have javascript run in my header or footer? Adam linked my issue #130 and I am unsure how your PR resolves that...

**Comment by geoffroya** [comment]
As the main html file is externalised, you can update it the way you want.

Best

**Pull request merged**
