### PR TITLE
Fix config directory permission validation

### LINKED ISSUE #87: Restarted Statping docker container always invokes setup page
Hi.

I run Statping-ng in docker with a persisted volume:
```
docker run -d \
  -v statping_data:/app \
  adamboutcher/statping-ng
```
However, if I restart the container (or create a new one with the same volume attached), Statping always lands on the `/setup` page asking for basic info. It doesn't "remember" info on the setup page, I have to reenter it every time.
Can we persist data in the `/setup` page too?

FYI, this problem existed in the original [statping/statping](https://github.com/statping/statping) repo too.
I hope it can be fixed here.

Thanks!

### PR DESCRIPTION
**Pull request by twouters**
Directories were reported as read-only as soon as the effective uid didn't the
match directory owner.

Rewrite permission validation to properly support UNIX permissions.

Does not support for Access Control Lists.

Fixes #87

### CODE REVIEW

**Comment by adamboutcher** [comment]
~~I'm not a go dev but this looks like you're checking the directory permissions and comparing to the user id?~~

~~Would it not be a better test to try and write and then fail gracefully? Just if the user has write permissions but isn't owner...~~

~~Let me know if I'm wrong though.~~

I think I understand this properly now, you test the uid, gid and other permissions.

**Comment by adamboutcher** [comment]
Looks good to me, @jemand771 can you have a quick once over? If it's good we can merge.

**Comment by jemand771** [comment]
while this looks way better than before, I'm not sure if it's perfect:
what happens when the user is the file owner but doesn't have write permissions set for themselves, but belong to a group with write access? I'm lacking some linux knowledge for this, but I *think* it should still be writable.
Same issue with the following: user is not the owner, group matches the file but doesn't have write perms, the file is writable by everyone

If the directory would still be writable, removing the two `else` branches would make the function more lenient accordingly

**Comment by twouters** [comment]
> while this looks way better than before, I'm not sure if it's perfect: what happens when the user is the file owner but doesn't have write permissions set for themselves, but belong to a group with write access? I'm lacking some linux knowledge for this, but I _think_ it should still be writable. Same issue with the following: user is not the owner, group matches the file but doesn't have write perms, the file is writable by everyone
> 
> If the directory would still be writable, removing the two `else` branches would make the function more lenient accordingly

It sounds counter intuitive, but that's not how it works.
I've made a bunch of directories with different ownership and permissions and attempted to write to them to validate the logic:

```
[twouters@testhost testdir]$ ls -Al
total 52
dr-xr-xr-x 2 twouters twouters 4096 Jan 24 06:51 dira
dr-xrwxr-x 2 twouters twouters 4096 Jan 24 06:51 dirb
dr-xr-xrwx 2 twouters twouters 4096 Jan 24 06:51 dirc
drwxr-xr-x 2 twouters twouters 4096 Jan 24 06:53 dird
drwxr-xr-x 2 root     twouters 4096 Jan 24 07:09 dire
dr-xrwxr-x 2 root     twouters 4096 Jan 24 07:13 dirf
dr-xr-xrwx 2 root     twouters 4096 Jan 24 07:09 dirg
drwxr-xr-x 2 twouters root     4096 Jan 24 07:13 dirh
dr-xrwxr-x 2 twouters root     4096 Jan 24 07:09 diri
dr-xr-xrwx 2 twouters root     4096 Jan 24 07:09 dirj
drwxr-xr-x 2 root     root     4096 Jan 24 07:10 dirk
dr-xrwxr-x 2 root     root     4096 Jan 24 07:10 dirl
dr-xr-xrwx 2 root     root     4096 Jan 24 07:13 dirm

[twouters@testhost testdir]$ for dir in $(ls -A); do touch "$dir"/write && echo "$dir is writable"; done
touch: cannot touch 'dira/write': Permission denied
touch: cannot touch 'dirb/write': Permission denied
touch: cannot touch 'dirc/write': Permission denied
dird is writable
touch: cannot touch 'dire/write': Permission denied
dirf is writable
touch: cannot touch 'dirg/write': Permission denied
dirh is writable
touch: cannot touch 'diri/write': Permission denied
touch: cannot touch 'dirj/write': Permission denied
touch: cannot touch 'dirk/write': Permission denied
touch: cannot touch 'dirl/write': Permission denied
dirm is writable
```

**Comment by twouters** [comment]
When I wrote this patch, I found out that the snippet is copied from a stackexchange answer: https://stackoverflow.com/questions/20026320/how-to-tell-if-folder-exists-and-is-writable

I've thought about just attempting to open a file and write to it to validate the permissions but I figured I shouldn't change the design of the function too much.  It might be better to do it anyway because it would be able to detect read-only mountpoints and ACL permissions.

**Comment by adamboutcher** [comment]
It looks/sounds good to me; I've taken a read on my desktop (which is far easier to read code on) and everything makes sense and your tests look sane.

Thanks for your efforts!

I'll merge this into 0.90.80 (once the unstable release has built as I've literally just merged for 0.90.79).

**Comment by jemand771** [comment]
oh wow, that _is_ counter-intuitive. thanks for the in-depth test :)

**Review by jemand771 — APPROVED** [review]

**Pull request merged**
