### PR TITLE
Add HEAD method to services

### LINKED ISSUE #143: [Feature Request] Allow HEAD http request
Hello.
You can use HEAD request type for get service status. In latest version HEAD request type not supported.

HEAD is most lightway request type. And can be used for more often status checks. Because in response it get only HTTP headers without data.

Please add HEAD request type to statping.

### PR DESCRIPTION
**Pull request by sndrr**
So services can use the HEAD method to check websites. This has the added benefit of not loading big pages and thus being more lightweight.

closes #143

### CODE REVIEW

**Comment by adamboutcher** [comment]
Thanks!

**Review by jemand771 — APPROVED** [review]
I added some services using head requests, looks like they all behave as expected:
image

lgtm! :D

**Comment by adamboutcher** [comment]
Does it actually use head in the http request or does it fall back to get? Just thi King incase the backend falls back to get on an unknown input?

Otherwise it's perfect and should be merged.

**Comment by jemand771** [comment]
good call! I checked with a local nginx instance and the requests actually come in as HEAD. so all good :)

**Comment by sndrr** [comment]
As noted in #143, I've tested this too. [Requests come in as HEAD](https://github.com/statping-ng/statping-ng/issues/143#issuecomment-1203740781)

**Pull request merged**
