### PR TITLE
Fix non admin local users login

### LINKED ISSUE #66: Unable to login as admin - stuck loading
We notice that after some week from a fresh installation, both sqlite and mysql, we are unable to login as admin, this remain in loading state forever.

We notice that also the home page of statping, the one showing all service status, remain in loading state forever.

Checking logs, stateping is working normally, it's checking service and so on, but we still face this problem.

We have many services, a mysqldump it's around 70mb, machine load and resources are good.

### LINKED ISSUE #93: Basic Auth Loop
I've set a basic auth username and password. When I open the app and enter the site again asks for credentials - some sort of login loop.

### LINKED ISSUE #148: Non admin user login
Hello,

With a non admin user i seem to get an error when logging in to the dashboard

```
api/users/token:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.chunk.js:1 Error: Request failed with status code 500
    at t.exports (vendor.chunk.js:23:46270)
    at t.exports (vendor.chunk.js:48:17769)
    at d.onreadystatechange (vendor.chunk.js:23:45122)
(anonymous) @ main.chunk.js:1
api/checkins:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
vendor.chunk.js:7 Error: Request failed with status code 401
    at t.exports (vendor.chunk.js:23:46270)
    at t.exports (vendor.chunk.js:48:17769)
    at d.onreadystatechange (vendor.chunk.js:23:45122)
```

Changing the user to an admin fixes the issue but I would rather people not have admin permissions to add incident messages

### PR DESCRIPTION
**Pull request by RoryDoherty**
I believe this resolves these issues 
https://github.com/statping-ng/statping-ng/issues/93 and https://github.com/statping-ng/statping-ng/issues/148

Logging in using the local authentication with a non admin user works and allows read only access

### CODE REVIEW

**Comment by RoryDoherty** [comment]
Closing in favour of https://github.com/RoryDoherty/statping-ng/pull/3

**Comment by adamboutcher** [comment]
Does this change the API?

Thank you btw for your contribution.

**Comment by RoryDoherty** [comment]
From my testing it will now allow an authenticated user read access to all resources via the api
An Admin user's permissions have not been affected

**Comment by MaxHayman** [comment]
@adamboutcher Could we get a docker image for the master branch? Would be awesome to be able to test the bleeding edge changes between releases.

**Comment by WilliamRoxit** [comment]
It would be really nice indeed if at least this change is merged and deployed to docker-image very soon

**Comment by adamboutcher** [comment]
The build scripts are currently failing and I dont have time to investigate it but I will merge this as it looks sane to me.

**Comment by adamboutcher** [comment]
Oh, it's already merged into dev. I just need to fix the build scripts then.

**Comment by WilliamRoxit** [comment]
That would be really great! The build logs are not available in github anymore so I don't think I can be of much assistance.

**Comment by jemand771** [comment]
fyi I've picked the workflow stuff™ back up after kinda giving up last year. no eta yet as other things keep coming up D:

**Pull request merged**
