### PR TITLE
Reset notifyAfterCount on Success

### PR DESCRIPTION
**Pull request by glanchow**
See Issue https://github.com/statping/statping/issues/911

### CODE REVIEW

**Comment by jemand771** [comment]
hi there and thanks for you contribution! :)

I've looked at the linked issue and your change and this seems to be a valid fix for it. I didn't have time to test it yet, though.
quick follow-up: from what I can see, `s.notifyAfterCount` isn't used anywhere else (such as a global fail counter etc.) - in that case, [line 83](https://github.com/statping-ng/statping-ng/pull/67/files#diff-5c6cd2f6a751baa0473af5e17bdd72805791cf76b22a2f21c02a6f0be49a6cbaR83) seems to be redundant since the counter is already incremented above. (likely a copy/paste error, same as the one you fixed)

do you see anything against removing that aswell while we're at it?

**Comment by glanchow** [comment]
Hi, thank you for your fast answer.
I think that this notifyAfterCount line 83 is executed when NotifyAfter == 0, the previous notifyAfterCount line 61, executed when NotifyAfter != 0, is followed by a return statement.

**Comment by jemand771** [comment]
yeah, `s.notifyAfterCount` gets incremented in line 83 if `s.NotifyAfter` is 0, in which case there is no need to keep track of the count there

I could imagine somebody adding a feature that uses this counter (e.g. "resettable" notifiers) at some point, so I don't really care if we leave it in or not ^^

**Comment by glanchow** [comment]
oh yes, I misunderstood your point the first time I read it
I agree and I will remove it right away

**Comment by jemand771** [comment]
okay, my testing setup for this was really manual, but this PR seems to fix the mentioned issue 🎉 

note: I feel like notifiers were wonky in general, especially the reported time (e.g. `292 years 24 weeks`). not related to this PR though

**Review by jemand771 — APPROVED** [review]

**Comment by adamboutcher** [comment]
@jemand771 we good to merge this?

**Comment by jemand771** [comment]
@adamboutcher oh yeah, this is good to go ^^

as a general workflow question - should I just merge PRs that look good to me (if I feel like I'm able to judge that) by myself or assign to you or..? I feel like we haven't really talked about that yet

**Comment by adamboutcher** [comment]
For now, if you think its a good pr then why not just merge, we can always roll back. Maybe in the future we just need two reviewers (especially if someone else with go knowledge steps up)

**Comment by glanchow** [comment]
I tested this version in production for a few weeks and it works well. You can merge

**Comment by jemand771** [comment]
just as a side note, the commit that was added after my review (6a80260) slightly changed the behaviour of the code:
when a notifier fails (for some reason), the states are updated anyway. (previously, they would only be updated after all notifiers had been processed)

this way, if a notifier fails, statping won't retry notifying anymore and will instead think that it has already done that.

I don't see how a notifier _would_ even fail temporarily, so it might not matter. (we don't want to retry for permanently broken notifiers)
just in case we see dropped notifications at some point, this might be related

**Comment by adamboutcher** [comment]
The notifiers that depends on 3rd party services could fail, such as the "Mail".

**Comment by glanchow** [comment]
yes I did this on purpose
imho a success should reset the retry counter, even if one of possible multiple notifiers is broken
if there is a need to retry notifications we should had more logic

**Pull request merged**
