### PR TITLE
Allow chat_ids for telegram notifications

### PR DESCRIPTION
**Pull request by nilshee**
Allow chat_ids in notifier. Currently you can not supply chat_ids for telegram notifications. This results in the inability to use private channels or groups for notifications.

### CODE REVIEW

**Comment by adamboutcher** [comment]
Thanks, once we're ready with the builds, we'll merge this.

**Comment by adamboutcher** [comment]
Just reviewing the commit, I'm curious to why you need an exception for the input to be numeric and not telegram.

~~If the chat Id 1234 then the input is numeric and parsed as such, if its -1234 then the input isn't numeric.~~

~~Or am I missing something?~~

Ignore me, I forgot negative numbers existed. I do however wonder why it doesn't work anyway and surely parseint just makes sure it's a valid integer negative or not? Or is this something to do with large ints?

**Comment by nilshee** [comment]
Well it converts the string into a number, which results in a "malformed Json format error" for telegram because it expects a string and it can not implicit convert it. So you need to escape it for telegram. 
Another notifier seems to need numeric values in it's Json.

**Comment by adamboutcher** [comment]
> which results in a "malformed Json format error" for telegram because it expects a string and it can not implicit convert it.

Oh the joys, this makes sense.

**Review by adamboutcher — APPROVED** [review]

**Comment by adamboutcher** [comment]
Should be able to test these changes in the artifacts (once built) at https://github.com/statping-ng/statping-ng/actions/runs/1233703972

**Pull request merged**
