### PR TITLE
Unstable v0.90.80 to Stable v0.90.80

### LINKED ISSUE #125: V0.90.80 Docker build fails
Docker build is failing on stable action.

### PR DESCRIPTION
**Pull request by adamboutcher**

### CODE REVIEW

**Comment by adamboutcher** [comment]
@jemand771 Can you review?

**Review by jemand771 — APPROVED** [review]
LGTM

**Comment by jemand771** [comment]
just as a side note: some of the commits in this PR are quite old because they were brought over from an old branch and only merged now (it looks off, but it's completely fine)
e.g. https://github.com/statping-ng/statping-ng/commit/69e4d7aa392e11708a5ecdbed39cb68d822c9693

**Comment by adamboutcher** [comment]
Thanks, good spot!

**Pull request merged**
